MMilestone 1
cgcarlosg/app-calculator1978 pull request #5
Opened 2021-07-08 01:35 UTC by cgcarlosg

2021-07-08 03:19 UTC, rindrajosia requested changes
Invalid 🔴 
The PR description is empty

2021-07-08 15:12 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @cgcarlosg, great job on this milestone :1st_place_medal: :smile: React svg logo and some unnecessary files have been deleted :+1: 
However, there are a few changes we need to effect before proceeding, let us kindly address the comments below:

- For the README file to be professional, we need to add the title of the project, tools/technologies used, packages install, how to run the app locally, social handles of the author, etc
- Kindly add the Big.js and Prop-Types packages to the package.json file
- Kindly deploy the app and include it in the README file
-  App does not run correctly with the "npm start" command. It returns "failed to compile" error and it gives further details "Failed to load config "airbnb" to extend from /app-calculator1978/.eslintrc.json"

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-07-09 06:27 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes. 
### Highlights 🌵 🌵 🌵 
- readme updated
- app can start locally
- packages added to `package.json` file

### Change(s) 🔕 🔕 🔕 
- update the readme file. make it more professional


### Martin Afani
#### Slack: whiz25

2021-07-09 06:27 UTC, afanimartin commented on README.md
> +Download the code or copy the git repository to your computer.
- Write the exact command for doing this. Be explicit in your instructions.

2021-07-09 06:27 UTC, afanimartin commented on README.md
> +To install dependencies you need to run the following command in your terminal.
- What's the command for doing that?

2021-07-09 06:27 UTC, afanimartin commented on README.md
> +npm test
- Learn to format your readme professionally. Check out some tips [here](https://www.makeareadme.com/)

2021-07-09 06:27 UTC, afanimartin commented on README.md
> +Live Preview
- Add a link to the deployed app.

2021-07-10 07:01 UTC, uche-inyama approved these changes
## Approved :heavy_check_mark: 

### Hi Carlos :slightly_smiling_face: 

Go on with your next milestone.


[**Note**] The image in your readme is not well formatted, it is currently broken.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-07-10 11:52 UTC, closed without merging

2021-07-10 11:52 UTC, cgcarlosg commented
Approved